### ISSUE TITLE
TheBlaze

### ISSUE THREAD

**Issue by Joannie418** [divingmule/plugin.video.theblaze#2]
Hi, I cannot get TheBlaze to open using kodi 17.3.  It just states that there is an error.  Is anyone else having an issue?  Please Help.  Thanks,  Jonnie418

**Comment by wyatt-herkamp** [comment]
I am having this issue? Is this what your log saying?
`20:34:18.651 T:140310358750976   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not callable
                                            Traceback (most recent call last):
                                              File "/home/wherkamp/.kodi/addons/plugin.video.theblaze/default.py", line 602, in <module>
                                                display_shows()
                                              File "/home/wherkamp/.kodi/addons/plugin.video.theblaze/default.py", line 94, in display_shows
                                                data = cache.cacheFunction(cache_shows)
                                              File "/home/wherkamp/.kodi/addons/script.common.plugin.cache/lib/StorageServer.py", line 570, in cacheFunction
                                                ret_val = funct(*args)
                                              File "/home/wherkamp/.kodi/addons/plugin.video.theblaze/default.py", line 82, in cache_shows
                                                shows_tag = content('div', attrs={'id': 'secondaryPlaylist_1'})[0]('div', attrs={'class': 'page topic item'})
                                            TypeError: 'NoneType' object is not callable
                                            -->End of Python script error report<--
20:34:18.785 T:140312467395072   ERROR: GetDirectory - Error getting plugin://plugin.video.theblaze/
20:34:18.786 T:140312467395072   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.theblaze/) failed
`

**Comment by dwizard0** [comment]
Hey man. What needs to happen to get this addon working again. Please reach out and let us know

**Comment by ghost** [comment]
I've got a WIP merge request in progress ( #3 ), and I would appreciate some testing (it is very much a WIP, but it is at least working for standard recorded shows, livestreams are not currently working).
